{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Количество регистраций за минуту",
   "type": "timeseries",
   "description": "График количества регистраций за минуту",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "user_registrations_total_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество бронирований",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "booking_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество регистраций",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_registrations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество входов за минуту",
   "type": "timeseries",
   "description": "График количества входов на сайт за минуту",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "user_logins_total_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество ошибок API за минуту",
   "type": "timeseries",
   "description": "График количества ошибок API за минуту",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "api_errors_total_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество бронирований за минуту",
   "type": "timeseries",
   "description": "График количества бронирований за минуту",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "booking_total_1m", "legendFormat": "__auto" }
   ]
  }
 ]
}