"""Initial migration

Revision ID: 12cf8bf36536
Revises: 875a3fb13b60
Create Date: 2025-03-03 12:04:41.056708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cf8bf36536'
down_revision: Union[str, None] = '875a3fb13b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'seats', ['seat_id'], ['id'])
    op.add_column('tickets', sa.Column('seat_name', sa.String(), nullable=True))
    op.alter_column('tickets', 'reservation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tickets', 'seat_id')
    op.drop_column('users', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('seat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('tickets', 'reservation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tickets', 'seat_name')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    # ### end Alembic commands ###
