"""Initial migration

Revision ID: 262d9b574821
Revises: 12cf8bf36536
Create Date: 2025-03-03 13:10:48.502970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262d9b574821'
down_revision: Union[str, None] = '12cf8bf36536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'seats', ['seat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'seat_id')
    # ### end Alembic commands ###
