"""Initial migration

Revision ID: 451a2a832929
Revises: 262d9b574821
Create Date: 2025-03-03 14:56:52.901828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451a2a832929'
down_revision: Union[str, None] = '262d9b574821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_seat_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_seat_id_fkey', 'tickets', 'seats', ['seat_id'], ['id'])
    # ### end Alembic commands ###
