"""Initial migration

Revision ID: 4e3f0d8281a3
Revises: e578e6ce7ec7
Create Date: 2025-03-01 12:23:02.782479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3f0d8281a3'
down_revision: Union[str, None] = 'e578e6ce7ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
