"""Initial migration

Revision ID: 53c886f44cfc
Revises: 004a760f3d59
Create Date: 2025-03-01 10:38:48.934235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c886f44cfc'
down_revision: Union[str, None] = '004a760f3d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('start', sa.DateTime(), nullable=False))
    op.add_column('reservations', sa.Column('end', sa.DateTime(), nullable=False))
    op.drop_column('reservations', 'date')
    op.drop_column('reservations', 'start_time')
    op.drop_column('reservations', 'end_time')
    op.create_unique_constraint(None, 'seats', ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'seats', type_='unique')
    op.add_column('reservations', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'end')
    op.drop_column('reservations', 'start')
    # ### end Alembic commands ###
