"""Initial migration

Revision ID: 572c891918c7
Revises: c54b3f9ced0e
Create Date: 2025-03-02 21:12:44.033650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572c891918c7'
down_revision: Union[str, None] = 'c54b3f9ced0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('avatar_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    op.drop_column('seats', 'name')
    # ### end Alembic commands ###
