"""Initial migration

Revision ID: 875a3fb13b60
Revises: 572c891918c7
Create Date: 2025-03-02 21:51:39.749292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a3fb13b60'
down_revision: Union[str, None] = '572c891918c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('seats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('seats', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('seats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('seats', 'type')
    # ### end Alembic commands ###
