"""Initial migration

Revision ID: c54b3f9ced0e
Revises: 6a7815b5acbd
Create Date: 2025-03-02 17:59:58.929649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54b3f9ced0e'
down_revision: Union[str, None] = '6a7815b5acbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_users_telegram_id', table_name='telegram_users')
    op.drop_index('ix_telegram_users_user_id', table_name='telegram_users')
    op.drop_table('telegram_users')
    op.add_column('users', sa.Column('telegram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.create_table('telegram_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='telegram_users_pkey')
    )
    op.create_index('ix_telegram_users_user_id', 'telegram_users', ['user_id'], unique=True)
    op.create_index('ix_telegram_users_telegram_id', 'telegram_users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
