"""Initial migration

Revision ID: e578e6ce7ec7
Revises: 53c886f44cfc
Create Date: 2025-03-01 10:50:46.008592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e578e6ce7ec7'
down_revision: Union[str, None] = '53c886f44cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('has_computer', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('has_water', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('has_kitchen', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('has_smart_desk', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('is_quite', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('is_talk_room', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'is_talk_room')
    op.drop_column('seats', 'is_quite')
    op.drop_column('seats', 'has_smart_desk')
    op.drop_column('seats', 'has_kitchen')
    op.drop_column('seats', 'has_water')
    op.drop_column('seats', 'has_computer')
    # ### end Alembic commands ###
