global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - recording_rules.yml

scrape_configs:
  - job_name: 'booking_server'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['server:8080']
